### ISSUE TITLE
When are you going to release it?

### ISSUE THREAD

**Issue by TraderChinese** [Mcash-project/Mcash#1]
What's the total and what's the algorithm?
Is there a website?
Are you serious?

**Comment by mateocabanal** [comment]
The cryptocurrency is in a working state now. It uses cryptonight as the pow algorithm.
I am currently making a blockchain explorer for it now

**Comment by TraderChinese** [comment]
> 加密货币现在处于工作状态。它使用加密夜作为 pow 算法。
> 我目前正在为它制作一个区块链资源管理器

 ERROR   insertion of new alternative block returned as it already exist
 WARNING Failed to push ex-main chain blocks to alternative chain
 INFO    REORGANIZE SUCCESS! on height: 2430, new blockchain size: 2431
 INFO    REORGANIZE SUCCESS! on height: 2430, new blockchain size: 2431
 INFO    ###### REORGANIZE on height: 2430 of 2430 with cum_difficulty 57421898
 INFO     alternative blockchain size: 1 with cum_difficulty 57421914
 INFO    ###### REORGANIZE on height: 2430 of 2430 with cum_difficulty 57421898
 INFO     alternative blockchain size: 1 with cum_difficulty 57421914


What's the total? 700 coins per block.
Do you have a discord, telegram?

**Comment by mateocabanal** [comment]
The total money supply is 3689348800000.

I do not have a discord server, but I am open to making one
